# Site settings
## Change the values as needed.
title: Colin Atkinson
email: 114d71d1@opayq.com
description: > # this means to ignore newlines until "keywords:"
  This is Colin\'s personal page. For contact info, see the about page.
keywords: "some, relevant, keywords, for, usage, in metatags"
# url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown:            redcarpet
highlighter:         pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: colin.william.atkinson
  twitter: colinatkinson65
  email: 114d71d1@opayq.com
  github: colatkinson
exclude:
  - bower_components
  - README.md
full_name: Colin Atkinson

##set this to enable disqus commenting
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
